### ISSUE TITLE
Auto-Export of file

### ISSUE THREAD

**Issue by ghost** [tmcw/heard#8]
It would be really nice if this auto-exported to a file that you can specify the location.  The idea being that I could put the file in dropbox and sync my music listening experience across all the machines I use, ie work, home, etc.

**Comment by tmcw** [comment]
True, [minute-agent](https://github.com/tmcw/minute-agent) works that way. I'll look into it, though that'll incur some cost of having configuration & unclear speed problems if it exports JSON per-song - with lots of plays (I have 5k) it'd be a pretty significant operation.

**Comment by ghost** [comment]
Have it default to a location in the users library folder, so they don't have to configure, but you give an option to override.

Chris Newton
e:  wreck@me.com
p:  (310) 990-5567
fb: apermanentwreck
t:   @apermanentwreck

**Comment by tmcw** [comment]
Happy to accept a PR implementing this change, but unlikely to get the time to do it myself!
